name: UnitTest

on: [ push ]

jobs:
  build:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: '5.6.1'
      - name: Build source code
        run: swift build
      - name: Run tests
        run: swift test --filter "SolanaSwiftUnitTests"