name: Up version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'     
        required: true

jobs:
  upversion:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3

    - name: upversion
      run: |
        brew install gnu-sed
        ./upversion ${{ github.event.inputs.version }}
